on:
  schedule:
    - cron: '10 19 * * 1,2,3,4,5'
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

name: WLS Daily COVID Note

jobs:
  render:
    name: Automate COVID Note
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies and packages
        run: Rscript -e 'install.packages(c("readr","dplyr","lubridate","htmlwidgets"))'
      - name: Gather data and save as text file
        run: Rscript scripts/chi_covid_note.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'New COVID note saved' || echo "No changes"
          git push origin || echo "No changes to commit"
      - name: Send email with contents
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Daily COVID Note for WLS
          to: Adriana.M.Cortez@abc.com,Alexandria.L.Jud@abc.com,Colin.D.Evans@abc.com,David.F.Fell@abc.com,Douglas.Whitmire@abc.com,Fiesha.Y.Burge@abc.com,Jennifer.C.Hoppenstedt@abc.com,Jennifer.L.Graves@abc.com,John.L.Silvey@abc.com,Neil.J.Woulfe@abc.com,Nneka.I.Nwosu@abc.com,Patrice.M.Folke@abc.com,Richard.E.Hillengas@abc.com,Virginia.R.Matos@abc.com,Wilson.Toy@abc.com,virginia.r.matos@abc.com,christine.m.tressel@abc.com,barbara.a.markoff@abc.com,arlene.p.erves@abc.com,john.a.klein@abc.com,christopher.j.parrish@abc.com,carleen.r.mosbach@abc.com,timothy.x.sallinger@abc.com,kristin.l.hoogenboom@abc.com,sara.m.tenenbaum@abc.com,ross.e.weidner@abc.com,jonathan.p.fagg@abc.com,Poinesha.A.Barnes@abc.com,Jamee.T.GartonInsko@abc.com
          from: ABC OTV Data Team # <abcotvdatateam@gmail.com>
          secure: true
          # body: Words
          # Optional HTML body read from file:
          html_body: file://covidnote.html
          # Optional carbon copy recipients:
          cc: john.l.kelly@abc.com, jkelly3rd@gmail.com
          # Optional recipient of the email response:
          # reply_to: john.l.kelly@abc.com
          convert_markdown: true
